### ISSUE TITLE
How and where did you include the metrics’ definition in evaluation 

### ISSUE THREAD

**Issue by tywei08** [EmoCareAI/ChatPsychiatrist#3]
I'm wondering where did you tell gpt4 to consider the 7 metrics you defined in the paper. I didn't see relevant message in the prompt in the judge_prompts.jsonl file. 

Thanks.

**Comment by Junemengyuan** [comment]
Hi, you can refer to the figure in the paper
<img width="501" alt="image" src="https://github.com/EmoCareAI/ChatPsychiatrist/assets/44728175/1ce19aaf-33a3-46a6-8f45-10f1d15005cc">

We define the counseling strategy and provide examples as shown in [Evaluation_definetion](https://github.com/EmoCareAI/ChatPsychiatrist/blob/master/docs/Evaluation_definetion.md)

**Comment by tywei08** [comment]
Thank you. I read the paper and your github repo carefully. I'm curious how you put these information in the code? Could you release this part of the code?

**Comment by Junemengyuan** [comment]
We will rearchive this part of code. When it's ready, we will notify you.
Basically, it's just a prompt completion.
