### ISSUE TITLE
Document prompt template in readme

### ISSUE THREAD

**Issue by kaladivo** [EmoCareAI/ChatPsychiatrist#4]
Hello, it would be very useful for others, if you document prompt template. 

I was trying to run the model using Ollama and I was able to run it, but it was quite tedious to find out which prompt template does FastChat use. 

This is the template I have used for Ollama (in Modelfile). Whitout this, the model does not work.
```
TEMPLATE """
### Human: {{.Prompt}}
### Assistant:
"""%  
```

Could you please document this in readme? (if this is the correct template of course)

**Comment by CiaoHe** [comment]
Please refer to the vicuna doc: https://github.com/lm-sys/FastChat/blob/00d9e6675bdff60be6603ffff9313b1d797d2e3e/fastchat/conversation.py#L115-L124
and https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md#prompt-template
