### ISSUE TITLE
Categroy Label Not Found

### ISSUE THREAD

**Issue by mianzhang** [EmoCareAI/ChatPsychiatrist#7]
Hi,

Congrats to the good work. However, I could not the category labels for the dataset. Could you tell me where can I find it?
<img width="888" alt="image" src="https://github.com/user-attachments/assets/20db95bd-09a8-404a-8399-7d78900948d5">

Best

**Comment by CiaoHe** [comment]
Sorry, we just mixed all categories of data. We'll find a way to recover the topic / label (human evaluation is torturous)
